#ifndef PHONEBOOK_CONSTANTS_H
#define PHONEBOOK_CONSTANTS_H

#define PHONEBOOK_NAME_MAX_LENGTH 32
#define PHONEBOOK_SURNAME_MAX_LENGTH 32
#define PHONEBOOK_PHONE_MAX_LENGTH 32
#define PHONEBOOK_EMAIL_MAX_LENGTH 32

#endif // PHONEBOOK_CONSTANTS_H

