#ifndef PHONEBOOK_CONSTANTS_H
#define PHONEBOOK_CONSTANTS_H

#define PHONEBOOK_NAME_MAX_LENGTH 32
#define PHONEBOOK_SURNAME_MAX_LENGTH 32
#define PHONEBOOK_PHONE_MAX_LENGTH 32
#define PHONEBOOK_EMAIL_MAX_LENGTH 32

#define PB_ADD 0
#define PB_DEL 1
#define PB_GET 2

#define PB_OK 0
#define PB_FAIL 1

#endif // PHONEBOOK_CONSTANTS_H

